---
- name: Deploy Apps to Network Lab
  hosts: all
  gather_facts: false
  become: yes
  vars:
    resource_group: networkascode

  vars_files:
    - vars.yml
    
  tasks:
    - debug: var=infra.repos.linux[inventory_hostname]
    
    - name: Add GPG apt Key
      apt_key:
        url: "{{ item.url }}"
        state: "{{ item.state }}"
      with_items: "{{ infra.repo_keys.linux[inventory_hostname] }}"
    
    - name: Add Repositories
      apt_repository:
        repo: deb {{ item.url }}
        state: "{{ item.state }}"
      with_items: "{{ infra.repos.linux[inventory_hostname] }}"
    
    - name: Add Apt Applications
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        update_cache: yes
        force_apt_get: yes
      with_items: "{{ infra.apps.linux[inventory_hostname].apt }}"
      
    - name: Add Python Applications
      pip:
        name: "{{ item.name }}"
      with_items: "{{ infra.apps.linux[inventory_hostname].pip }}"